import { build } from "esbuild";
import assert from "node:assert/strict";
import { mkdir, readFile } from "node:fs/promises";
import { TransactionFixture } from "./transaction-fixture.mjs";
await mkdir("outputs", { recursive: true });
await build({ stdin: { contents: 'export * from "./lib/server-quota.ts"; export * from "./lib/server-projects.ts"; export * from "./lib/ai-quality.ts"; export * from "./lib/prd.ts"; export * from "./lib/clarification.ts"; export * from "./lib/tech-stack.ts"; export * from "./lib/server-store.ts"; export * from "./lib/project-firestore-codec.ts";', resolveDir: process.cwd() }, bundle: true, platform: "node", format: "esm", outfile: "outputs/quota-test-module.mjs", plugins: [{ name: "runtime-fixture", setup(b) { b.onResolve({ filter: /^cloudflare:workers$/ }, () => ({ path: "env", namespace: "fixture" })); b.onLoad({ filter: /.*/, namespace: "fixture" }, () => ({ contents: 'export const env = {};', loader: "js" })); } }] });
const m = await import("../outputs/quota-test-module.mjs");
const policy = { freeLimit: 1, proLimit: 30, freeMonthly: false }, db = new TransactionFixture();
let now = Date.parse("2026-10-07T00:00:00Z");
const clock = () => now, quota = m.quotaService(db, policy, clock), projects = m.projectService(db, policy, clock);
const draft = { ...m.newDraft("Aplikasi stok toko kecil untuk mencatat barang masuk dan keluar."), answers: [["Pemilik toko"], ["Daftar barang"], ["Catat barang masuk"], ["Nyaman di ponsel"], ["Riwayat stok"]], completed: true, step: 4 };
const stack = m.recommendStack(draft).stack;
const raw = structuredClone(m.examplePRD(draft, stack));
raw.title = "Stok Toko Harian";
raw.phases.forEach(phase => phase.features.forEach(f => { f.description = `Pemilik toko menjalankan ${f.title} menggunakan SKU dan jumlah barang pada toko miliknya.`; f.subfeatures.forEach((task, i) => { task.title = i ? "Tolak jumlah stok negatif dan tampilkan pesan pada field jumlah" : "Simpan SKU, jumlah dan waktu transaksi barang ke akun toko"; }); }));
const validated = m.validateAI(raw, draft, stack);
const comparisons = structuredClone(raw);
comparisons.phases[0].features[0].acceptance[0] = { precondition: "Stok < 5 pada produk kopi dan jumlah masuk > 0.", action: "Pemilik menambahkan 2 barang.", expected: "Stok bertambah 2 setelah transaksi dikonfirmasi." };
assert(m.validateAI(comparisons, draft, stack), "Stock comparison operators are not placeholders");
const plan = { ...validated, source: "ai", model: "fixture", draft, stack, generatedAt: new Date(now).toISOString() };
for (const mutate of [p => { delete p.summary; }, p => { p.phases.pop(); }, p => { p.phases[0].features[0].title = "Fitur lain"; }, p => { p.phases[0].features[0].acceptance = ["Berhasil disimpan"]; }, p => { p.userFlows = []; }, p => { p.phases[0].features[0].description = "<deskripsi fitur>"; }, p => { p.phases[0].features[0].subfeatures = []; }]) {
  const bad = structuredClone(raw); mutate(bad);
  assert.throws(() => m.validateAI(bad, draft, stack), e => e.code === "ai-quality");
}
assert.throws(() => m.validateAI(m.examplePRD(draft, stack), draft, stack), e => e.code === "ai-quality");
const jobs = Array.from({ length: 12 }, () => crypto.randomUUID());
const raced = await Promise.allSettled(jobs.map(id => quota.reserve("free", id, "same-input")));
assert.equal(raced.filter(r => r.status === "fulfilled").length, 1);
assert(db.conflicts > 0, "Concurrent reads must produce transaction retries");
assert(raced.filter(r => r.status === "rejected").every(r => r.reason.code === "quota-exhausted"));
const winner = raced.findIndex(r => r.status === "fulfilled"), id = jobs[winner], lease = raced[winner].value.lease;
assert.deepEqual(await quota.snapshot("free"), { package: "free", status: "beta", readOnly: false, limit: 1, used: 0, reserved: 1, remaining: 0, expiresAt: null });
await assert.rejects(quota.reserve("free", id, "same-input"), e => e.code === "generation-pending");
await quota.release("free", id, lease);
assert.equal((await quota.snapshot("free")).remaining, 1, "Failure releases hold without debit");
const retry = await quota.reserve("free", id, "same-input");
const results = await Promise.all(Array.from({ length: 5 }, () => quota.complete("free", id, retry.lease, plan)));
assert(results.every(result => result.generationId === id));
assert.equal((await quota.snapshot("free")).used, 1);
await quota.release("free", id, retry.lease); // An ambiguous response must never undo a completed debit.
assert.equal((await quota.snapshot("free")).used, 1);
assert.equal((await m.quotaService(db, policy, clock).reserve("free", id, "same-input")).plan.generationId, id, "New server instance recovers durable result");
await assert.rejects(quota.reserve("free", id, "different-input"), e => e.code === "request-conflict");
await assert.rejects(quota.reserve("free", crypto.randomUUID(), "same-input"), e => e.code === "quota-exhausted");
const forged = { ...results[0], prd: { ...results[0].prd, title: "Forged title" } };
const saved = await projects.save("free", forged);
assert.equal(saved.prd.title, raw.title, "Server saves the confirmed result, not client supplied AI content");
const saves = await Promise.all(Array.from({ length: 8 }, () => projects.save("free", results[0])));
assert(saves.every(p => p.id === saved.id));
const tasks = m.taskList(saved.prd);
await Promise.all(tasks.slice(0, 2).map(t => projects.task("free", saved.id, t.id, true)));
const project = m.projectSchema.parse(m.decodeProjectFromFirestore(db.data.get(`users/free/projects/${saved.id}`)));
assert.equal(Object.keys(project.tasks).length, 2, "Concurrent checklist changes are merged atomically");
const encoded = m.encodeProjectForFirestore(project);
assert.deepEqual(m.projectSchema.parse(m.decodeProjectFromFirestore(m.decodeFields(m.encodeFields(encoded)))), project);
assert.throws(() => m.encodeValue([["invalid"]]), /Nested/);
await assert.rejects(projects.save("other", results[0]), e => e.code === "generation-receipt");
await assert.rejects(projects.task("other", saved.id, tasks[0].id, true), e => e.code === "project-missing");
await assert.rejects(projects.task("free", saved.id, "invented", true), e => e.code === "task-id");
const proStart = new Date(now).toISOString(), proEnd = new Date(now + 30 * 86400000).toISOString();
db.seed("users/pro/billing/account", { package: "pro", proStartedAt: proStart, proExpiresAt: proEnd });
const example = { ...plan, source: "example" };
const old = await projects.save("pro", example);
const proJob = crypto.randomUUID(), pending = await quota.reserve("pro", proJob, "pro-input");
now = Date.parse(proEnd);
assert.equal((await quota.snapshot("pro")).readOnly, true);
assert.equal((await quota.snapshot("pro")).remaining, 0);
await assert.rejects(projects.save("pro", { ...example, generatedAt: new Date(now).toISOString() }), e => e.code === "pro-expired");
await assert.rejects(projects.task("pro", old.id, tasks[0].id, true), e => e.code === "pro-expired");
await assert.rejects(projects.remove("pro", old.id), e => e.code === "pro-expired");
await assert.rejects(quota.reserve("pro", crypto.randomUUID(), "new"), e => e.code === "pro-expired");
await assert.rejects(quota.complete("pro", proJob, pending.lease, plan));
assert(db.data.has(`users/pro/projects/${old.id}`), "Expiration preserves old project");
assert(m.exportMarkdown(old).includes(raw.title), "Export remains independent from entitlement");
const expiringId = crypto.randomUUID(), first = await quota.reserve("lease", expiringId, "lease-input");
now += m.LEASE_MS + 1;
const replacement = await quota.reserve("lease", expiringId, "lease-input");
assert.notEqual(first.lease, replacement.lease);
await quota.release("lease", expiringId, first.lease);
assert.equal((await quota.snapshot("lease")).reserved, 1, "Old attempt cannot release a new lease");
await assert.rejects(quota.complete("lease", expiringId, first.lease, plan), e => e.code === "generation-state");
await quota.complete("lease", expiringId, replacement.lease, plan);
db.seed("users/broken/billing/account", { package: "pro", proExpiresAt: "invalid" });
await assert.rejects(quota.snapshot("broken"), e => e.code === "account-data");
db.seed("users/broken-quota/quota/free-lifetime", { used: -1 });
await assert.rejects(quota.reserve("broken-quota", crypto.randomUUID(), "input"), e => e.code === "quota-data");
await assert.rejects(quota.reserve("free", "../escape", "input"), e => e.code === "request-id");
await assert.rejects(quota.snapshot("../escape"), e => e.code === "session");
const monthly = m.quotaService(db, { ...policy, freeMonthly: true }, clock);
const monthId = crypto.randomUUID(), monthHold = await monthly.reserve("monthly", monthId, "input");
await monthly.complete("monthly", monthId, monthHold.lease, plan);
now = Date.parse("2026-12-01T00:00:00Z");
assert.equal((await monthly.snapshot("monthly")).remaining, 1);
// Every domain section and all checkbox states survive export, including table escaping.
project.prd.permissionMatrix = [{ role: "Free | uji", capability: "Stok\nbarang", rule: "Pemilik toko" }];
const markdown = m.exportMarkdown(project, project.tasks);
for (const heading of ["Pengguna", "Tujuan", "Di luar cakupan", "Tech stack", "User Flow", "Matriks izin", "Sistem desain", "Arsitektur teknis", "Model data", "Risiko", "Asumsi", "Keputusan terbuka", "Lampiran: ide awal"]) assert(markdown.includes(heading), heading);
for (const t of tasks) assert(markdown.includes(`- [${project.tasks[t.id] ? "x" : " "}] ${t.title}`));
for (const phase of project.prd.phases) for (const f of phase.features) for (const a of f.acceptance) for (const text of Object.values(a)) assert(markdown.includes(text));
assert(markdown.includes("Free \\| uji"));
const rules = await readFile("firestore.rules", "utf8");
assert(rules.includes("allow read: if request.auth != null && request.auth.uid == uid"));
assert(rules.includes("allow write: if false"));
console.log("PASS: strict AI validation; concurrent last-slot reservation; failure release; idempotent completion and retry recovery; lease fencing; owner isolation; server-confirmed save; concurrent tasks; expired Pro read/export; Firestore codec; complete Markdown export; monthly policy.");
